/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AssignmentOOSD1;

import AssignmentOOSD1.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CinemaTicketingSystem extends javax.swing.JFrame {

      private ArrayList<Customer> customers = new ArrayList<>();
      private ArrayList<Movie> movies = new ArrayList<>();
      private ArrayList<MovieShow> movieShows = new ArrayList<>();
      private ArrayList<String> theaters = new ArrayList<>();
      private ArrayList<TheaterHall> theaterHalls = new ArrayList<>();
       private ArrayList<Ticket> tickets = new ArrayList<>();
  
    public CinemaTicketingSystem() {
        initComponents();
        updateSelectMovieComboBox();
        updateTheaterComboBoxes();
        updateHallComboBoxForTheater();
        updateMovieShowComboBox();
        updateCustomerComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerIdField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        addCustomerBtn = new javax.swing.JButton();
        searchCustomerBtn = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        clearCustomerBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        movieIdField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        movieNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        languageField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        genreField = new javax.swing.JTextField();
        addMovieButton = new javax.swing.JButton();
        searchMovieBtn = new javax.swing.JButton();
        deleteMovieBtn = new javax.swing.JButton();
        clearMovieBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        movieShowDetailsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        selectMovieComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        datePlayingField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        timePlayingField = new javax.swing.JTextField();
        addMovieShowButton = new javax.swing.JButton();
        deleteMovieShowBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        theaterListTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        addTheaterField = new javax.swing.JTextField();
        addTheaterButton = new javax.swing.JButton();
        deleteTheaterBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        theaterHallTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        hallField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        listTheaterComboForHall = new javax.swing.JComboBox<>();
        addHallButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        CustomerLabel = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        MovieShowLabel = new javax.swing.JLabel();
        movieShowComboBox = new javax.swing.JComboBox<>();
        TheaterLabel = new javax.swing.JLabel();
        theaterComboForTicket = new javax.swing.JComboBox<>();
        HallLabel = new javax.swing.JLabel();
        hallComboBox = new javax.swing.JComboBox<>();
        SeatNumberLabel = new javax.swing.JLabel();
        seatNumberField = new javax.swing.JTextField();
        TicketIDLabel = new javax.swing.JLabel();
        ticketIdField = new javax.swing.JTextField();
        sellTicketButton = new javax.swing.JButton();
        searchTicketBtn = new javax.swing.JButton();
        deleteTicketBtn = new javax.swing.JButton();
        clearTicketBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Pictures\\pngtree-movie-ticket-cinema-poster-design-image_189806.jpg")); // NOI18N

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        jLabel3.setText("Customer ID:");

        jLabel4.setText("First Name:");

        jLabel5.setText("Last Name:");

        addCustomerBtn.setText("Add");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        searchCustomerBtn.setText("Search");
        searchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerBtnActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("Delete");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        clearCustomerBtn.setText("Clear");
        clearCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addCustomerBtn))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerIdField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(searchCustomerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCustomerButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearCustomerBtn)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(customerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerBtn)
                            .addComponent(searchCustomerBtn)
                            .addComponent(deleteCustomerButton)
                            .addComponent(clearCustomerBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Movie ID", "Movie Name", "Duration(Min)", "Language", "Genre"
            }
        ));
        jScrollPane4.setViewportView(movieTable);

        jLabel9.setText("Movie ID:");

        jLabel10.setText("Movie Name:");

        jLabel11.setText("Duration:");

        jLabel12.setText("Language:");

        jLabel13.setText("Genre:");

        genreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreFieldActionPerformed(evt);
            }
        });

        addMovieButton.setText("Add");
        addMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieButtonActionPerformed(evt);
            }
        });

        searchMovieBtn.setText("Search");
        searchMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMovieBtnActionPerformed(evt);
            }
        });

        deleteMovieBtn.setText("Delete");
        deleteMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieBtnActionPerformed(evt);
            }
        });

        clearMovieBtn.setText("Clear");
        clearMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMovieBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(languageField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieNameField)
                    .addComponent(movieIdField)
                    .addComponent(durationField)
                    .addComponent(genreField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(addMovieButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchMovieBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMovieBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearMovieBtn)))
                .addGap(61, 61, 61))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(movieIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(movieNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMovieButton)
                    .addComponent(searchMovieBtn)
                    .addComponent(deleteMovieBtn)
                    .addComponent(clearMovieBtn))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        jTabbedPane1.addTab("Movie", jPanel3);

        movieShowDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Movie Title", "Date Playing", "Time Playing"
            }
        ));
        jScrollPane5.setViewportView(movieShowDetailsTable);

        jLabel6.setText("Select Movie: ");

        selectMovieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectMovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovieComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter Date Playing:");

        jLabel8.setText("Enter Time Playing:");

        addMovieShowButton.setText("Add");
        addMovieShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieShowButtonActionPerformed(evt);
            }
        });

        deleteMovieShowBtn.setText("Delete");
        deleteMovieShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieShowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addMovieShowButton)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectMovieComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePlayingField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(timePlayingField))))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(deleteMovieShowBtn)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(selectMovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(datePlayingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(timePlayingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMovieShowButton)
                    .addComponent(deleteMovieShowBtn))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Movie Show", jPanel4);

        theaterListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Theater Name"
            }
        ));
        jScrollPane2.setViewportView(theaterListTable);

        jLabel17.setText("Theater:");

        addTheaterButton.setText("Add");
        addTheaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTheaterButtonActionPerformed(evt);
            }
        });

        deleteTheaterBtn.setText("Delete");
        deleteTheaterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTheaterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTheaterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTheaterField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTheaterBtn))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(addTheaterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTheaterButton)
                            .addComponent(deleteTheaterBtn)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Theater", jPanel5);

        theaterHallTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Theater Name", "Hall Number"
            }
        ));
        jScrollPane6.setViewportView(theaterHallTable);

        jLabel18.setText("Hall");

        jLabel19.setText("Theater");

        listTheaterComboForHall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addHallButton.setText("Add");
        addHallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHallButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(hallField))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(listTheaterComboForHall, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addHallButton)))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(listTheaterComboForHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hallField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(50, 50, 50)
                        .addComponent(addHallButton)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Theater Hall", jPanel6);

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ", "Movie Show", "Theater", "Hall", "Seat No."
            }
        ));
        jScrollPane7.setViewportView(ticketTable);

        CustomerLabel.setText("Customer:");

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MovieShowLabel.setText("Movie Show:");

        movieShowComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TheaterLabel.setText("Theater:");

        theaterComboForTicket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        HallLabel.setText("Hall:");

        hallComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SeatNumberLabel.setText("Seat Number:");

        TicketIDLabel.setText("Ticket ID:");

        sellTicketButton.setText("Sell Ticket");
        sellTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTicketButtonActionPerformed(evt);
            }
        });

        searchTicketBtn.setText("Search");
        searchTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTicketBtnActionPerformed(evt);
            }
        });

        deleteTicketBtn.setText("Delete");
        deleteTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTicketBtnActionPerformed(evt);
            }
        });

        clearTicketBtn.setText("Clear");
        clearTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MovieShowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TheaterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HallLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(seatNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(ticketIdField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerComboBox, 0, 231, Short.MAX_VALUE)
                            .addComponent(movieShowComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(theaterComboForTicket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hallComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(searchTicketBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellTicketButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteTicketBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearTicketBtn))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieShowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MovieShowLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theaterComboForTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TheaterLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hallComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HallLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeatNumberLabel)
                            .addComponent(seatNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ticketIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellTicketButton)
                            .addComponent(TicketIDLabel)
                            .addComponent(searchTicketBtn)
                            .addComponent(deleteTicketBtn)
                            .addComponent(clearTicketBtn))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Ticket", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cinema Ticketing System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
         
        String id = customerIdField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();

        if (id.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        Customer customer = new Customer(id, firstName, lastName);
        customers.add(customer);
        updateCustomerTable();
        updateCustomerComboBox();
        clearCustomerFields();
    }

    private void clearCustomerFields() {
        customerIdField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
    }

    private void updateCustomerTable() {
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        model.setRowCount(0);

        for (Customer customer : customers) {
            model.addRow(new Object[]{customer.getId(), customer.getFirstName(), customer.getLastName()});
        }
    
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void searchCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerBtnActionPerformed
        
        String id = customerIdField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();

        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        model.setRowCount(0);

        for (Customer customer : customers) {
            if (customer.getId().equals(id) || customer.getFirstName().equals(firstName) || customer.getLastName().equals(lastName)) {
                model.addRow(new Object[]{customer.getId(), customer.getFirstName(), customer.getLastName()});
            }
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No customer found.");
        }
    }//GEN-LAST:event_searchCustomerBtnActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
         
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a customer to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        String customerId = model.getValueAt(selectedRow, 0).toString();

        customers.removeIf(customer -> customer.getId().equals(customerId));
        updateCustomerTable();
        updateCustomerComboBox();
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void genreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreFieldActionPerformed

    }//GEN-LAST:event_genreFieldActionPerformed

      private void clearMovieFields() {
        movieIdField.setText("");
        movieNameField.setText("");
        durationField.setText("");
        languageField.setText("");
        genreField.setText("");
    }

    private void updateMovieTable() {
        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
        model.setRowCount(0);

        for (Movie movie : movies) {
            model.addRow(new Object[]{movie.getId(), movie.getName(), movie.getDuration(), movie.getLanguage(), movie.getGenre()});
        }
    }
    
    private void addMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieButtonActionPerformed
        
        String id = movieIdField.getText();
        String name = movieNameField.getText();
        String duration = durationField.getText();
        String language = languageField.getText();
        String genre = genreField.getText();

        if (id.isEmpty() || name.isEmpty() || duration.isEmpty() || language.isEmpty() || genre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        Movie movie = new Movie(id, name, duration, language, genre);
        movies.add(movie);
        updateMovieTable();
        updateSelectMovieComboBox();
        clearMovieFields();
    }//GEN-LAST:event_addMovieButtonActionPerformed

    private void searchMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMovieBtnActionPerformed
         
        String id = movieIdField.getText();
        String name = movieNameField.getText();
        String duration = durationField.getText();
        String language = languageField.getText();
        String genre = genreField.getText();

        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
        model.setRowCount(0);

        for (Movie movie : movies) {
            if (movie.getId().equals(id) || movie.getName().equals(name) || movie.getDuration().equals(duration) || movie.getLanguage().equals(language) || movie.getGenre().equals(genre)) {
                model.addRow(new Object[]{movie.getId(), movie.getName(), movie.getDuration(), movie.getLanguage(), movie.getGenre()});
            }
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No movie found.");
        }
    }//GEN-LAST:event_searchMovieBtnActionPerformed

    private void deleteMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieBtnActionPerformed
        
        int selectedRow = movieTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a movie to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
        String movieId = model.getValueAt(selectedRow, 0).toString();

        movies.removeIf(movie -> movie.getId().equals(movieId));
        updateMovieTable();
        updateSelectMovieComboBox();
    }//GEN-LAST:event_deleteMovieBtnActionPerformed

    private void updateSelectMovieComboBox() {
        selectMovieComboBox.removeAllItems();
        for (Movie movie : movies) {
            selectMovieComboBox.addItem(movie.getName());
        }
    }
    
    private void addMovieShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieShowButtonActionPerformed
        
        String movieTitle = (String) selectMovieComboBox.getSelectedItem();
        String datePlaying = datePlayingField.getText();
        String timePlaying = timePlayingField.getText();

        if (movieTitle == null || datePlaying.isEmpty() || timePlaying.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        MovieShow movieShow = new MovieShow(movieTitle, datePlaying, timePlaying);
        movieShows.add(movieShow);
        updateMovieShowTable();
        updateMovieShowComboBox();
        clearMovieShowFields();
    }//GEN-LAST:event_addMovieShowButtonActionPerformed

    private void deleteMovieShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieShowBtnActionPerformed
         
        int selectedRow = movieShowDetailsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a movie show to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) movieShowDetailsTable.getModel();
        String movieTitle = model.getValueAt(selectedRow, 0).toString();

        movieShows.removeIf(movieShow -> movieShow.getMovieTitle().equals(movieTitle));
        updateMovieShowTable();
        updateMovieShowComboBox();
    }//GEN-LAST:event_deleteMovieShowBtnActionPerformed

    private void clearMovieShowFields() {
        datePlayingField.setText("");
        timePlayingField.setText("");
        //selectMovieComboBox.setSelectedIndex(-1);
    }

    private void updateMovieShowTable() {
        DefaultTableModel model = (DefaultTableModel) movieShowDetailsTable.getModel();
        model.setRowCount(0);

        for (MovieShow movieShow : movieShows) {
            model.addRow(new Object[]{movieShow.getMovieTitle(), movieShow.getDatePlaying(), movieShow.getTimePlaying()});
        }
    }
    
    private void addTheaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTheaterButtonActionPerformed
        
        String theaterName = addTheaterField.getText();

        if (theaterName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a theater name.");
            return;
        }
            
        theaters.add(theaterName);
        updateTheaterTable();
        updateTheaterComboBoxes();
        addTheaterField.setText("");
    
    }//GEN-LAST:event_addTheaterButtonActionPerformed

    private void deleteTheaterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTheaterBtnActionPerformed
        
         int selectedRow = theaterListTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a theater to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) theaterListTable.getModel();
        String theaterName = model.getValueAt(selectedRow, 0).toString();

        theaters.remove(theaterName);
        updateTheaterTable();
        updateTheaterComboBoxes();
    }//GEN-LAST:event_deleteTheaterBtnActionPerformed

     private void updateTheaterTable() {
        DefaultTableModel model = (DefaultTableModel) theaterListTable.getModel();
        model.setRowCount(0);

        for (String theater : theaters) {
            model.addRow(new Object[]{theater});
        }
    }

    private void updateTheaterComboBoxes() {
        listTheaterComboForHall.removeAllItems();
        theaterComboForTicket.removeAllItems();

        for (String theater : theaters) {
            listTheaterComboForHall.addItem(theater);
            theaterComboForTicket.addItem(theater);
        }
    }
    
    private void addHallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHallButtonActionPerformed
        
        String theaterName = (String) listTheaterComboForHall.getSelectedItem();
        String hallNumber = hallField.getText();

        if (theaterName == null || hallNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
    }//GEN-LAST:event_addHallButtonActionPerformed
        TheaterHall theaterHall = new TheaterHall(theaterName, hallNumber);
        theaterHalls.add(theaterHall);
        updateTheaterHallTable();
        hallField.setText("");
        updateHallComboBoxForTheater();
    }
    
    private void updateTheaterHallTable() {
        DefaultTableModel model = (DefaultTableModel) theaterHallTable.getModel();
        model.setRowCount(0);

        for (TheaterHall theaterHall : theaterHalls) {
            model.addRow(new Object[]{theaterHall.getTheaterName(), theaterHall.getHallNumber()});
        }
    }
    
    private void updateMovieShowComboBox() {
       movieShowComboBox.removeAllItems();
    for (MovieShow movieShow : movieShows) {
        movieShowComboBox.addItem(movieShow.getMovieTitle() + " - " + movieShow.getDatePlaying() + " " + movieShow.getTimePlaying());
    }
    }
    
     private void updateCustomerComboBox() {
        customerComboBox.removeAllItems();
        for (Customer customer : customers) {
            customerComboBox.addItem(customer.getFirstName() + " " + customer.getLastName());
        }
    }
    
    private void updateHallComboBoxForTheater() {
        String selectedTheater = (String) theaterComboForTicket.getSelectedItem();
        hallComboBox.removeAllItems();
        for (TheaterHall hall : theaterHalls) {
            if (hall.getTheaterName().equals(selectedTheater)) {
                hallComboBox.addItem(hall.getHallNumber());
            }
        }
    }
        
    private void searchTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTicketBtnActionPerformed
        
        String ticketID = ticketIdField.getText();
        String customerName = (String) customerComboBox.getSelectedItem();

        DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
        model.setRowCount(0);

        for (Ticket ticket : tickets) {
            if (ticket.getTicketID().equals(ticketID) || ticket.getCustomerName().equals(customerName)) {
                model.addRow(new Object[]{ticket.getCustomerName(), ticket.getMovieShowTitle(), ticket.getTheaterName(), ticket.getHallNumber(), ticket.getSeatNumber()});
            }
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No ticket found.");
        }
    }//GEN-LAST:event_searchTicketBtnActionPerformed

    private void sellTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTicketButtonActionPerformed
       
        String customerName = (String) customerComboBox.getSelectedItem();
        String movieShowTitle = (String) movieShowComboBox.getSelectedItem();
        String theaterName = (String) theaterComboForTicket.getSelectedItem();
        String hallNumber = (String) hallComboBox.getSelectedItem();
        String seatNumber = seatNumberField.getText();
        String ticketID = ticketIdField.getText();

        if (customerName == null || movieShowTitle == null || theaterName == null || hallNumber == null || seatNumber.isEmpty() || ticketID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        Ticket ticket = new Ticket(customerName, movieShowTitle, theaterName, hallNumber, seatNumber, ticketID);
        tickets.add(ticket);
        updateTicketTable();
        clearTicketFields();
        
    }//GEN-LAST:event_sellTicketButtonActionPerformed

    private void updateTicketTable() {
        DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
        model.setRowCount(0);
        for (Ticket ticket : tickets) {
            model.addRow(new Object[]{ticket.getCustomerName(), ticket.getMovieShowTitle(), ticket.getTheaterName(), ticket.getHallNumber(), ticket.getSeatNumber()});
        }
    }

    private void clearTicketFields() {
        seatNumberField.setText("");
        ticketIdField.setText("");
        customerComboBox.setSelectedIndex(-1);
        movieShowComboBox.setSelectedIndex(-1);
        theaterComboForTicket.setSelectedIndex(-1);
        hallComboBox.setSelectedIndex(-1);
    }
    
    private void clearCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCustomerBtnActionPerformed
         
        clearCustomerFields();
        updateCustomerTable();
    }//GEN-LAST:event_clearCustomerBtnActionPerformed

    private void clearMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMovieBtnActionPerformed
        
        clearMovieFields();
        updateMovieTable();
    }//GEN-LAST:event_clearMovieBtnActionPerformed

    private void selectMovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectMovieComboBoxActionPerformed

    private void deleteTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTicketBtnActionPerformed
        
   int selectedRow = ticketTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a ticket to delete.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
    String customerName = model.getValueAt(selectedRow, 0).toString();
    String movieShowTitle = model.getValueAt(selectedRow, 1).toString();
    String theaterName = model.getValueAt(selectedRow, 2).toString();
    String hallNumber = model.getValueAt(selectedRow, 3).toString();
    String seatNumber = model.getValueAt(selectedRow, 4).toString();

    tickets.removeIf(ticket -> ticket.getCustomerName().equals(customerName) &&
                               ticket.getMovieShowTitle().equals(movieShowTitle) &&
                               ticket.getTheaterName().equals(theaterName) &&
                               ticket.getHallNumber().equals(hallNumber) &&
                               ticket.getSeatNumber().equals(seatNumber));
    updateTicketTable();
    }//GEN-LAST:event_deleteTicketBtnActionPerformed

    private void clearTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTicketBtnActionPerformed
        clearTicketFields();
    }//GEN-LAST:event_clearTicketBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CinemaTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CinemaTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CinemaTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinemaTicketingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinemaTicketingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JLabel HallLabel;
    private javax.swing.JLabel MovieShowLabel;
    private javax.swing.JLabel SeatNumberLabel;
    private javax.swing.JLabel TheaterLabel;
    private javax.swing.JLabel TicketIDLabel;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JButton addHallButton;
    private javax.swing.JButton addMovieButton;
    private javax.swing.JButton addMovieShowButton;
    private javax.swing.JButton addTheaterButton;
    private javax.swing.JTextField addTheaterField;
    private javax.swing.JButton clearCustomerBtn;
    private javax.swing.JButton clearMovieBtn;
    private javax.swing.JButton clearTicketBtn;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JTextField customerIdField;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField datePlayingField;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteMovieBtn;
    private javax.swing.JButton deleteMovieShowBtn;
    private javax.swing.JButton deleteTheaterBtn;
    private javax.swing.JButton deleteTicketBtn;
    private javax.swing.JTextField durationField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField genreField;
    private javax.swing.JComboBox<String> hallComboBox;
    private javax.swing.JTextField hallField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField languageField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JComboBox<String> listTheaterComboForHall;
    private javax.swing.JTextField movieIdField;
    private javax.swing.JTextField movieNameField;
    private javax.swing.JComboBox<String> movieShowComboBox;
    private javax.swing.JTable movieShowDetailsTable;
    private javax.swing.JTable movieTable;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JButton searchMovieBtn;
    private javax.swing.JButton searchTicketBtn;
    private javax.swing.JTextField seatNumberField;
    private javax.swing.JComboBox<String> selectMovieComboBox;
    private javax.swing.JButton sellTicketButton;
    private javax.swing.JComboBox<String> theaterComboForTicket;
    private javax.swing.JTable theaterHallTable;
    private javax.swing.JTable theaterListTable;
    private javax.swing.JTextField ticketIdField;
    private javax.swing.JTable ticketTable;
    private javax.swing.JTextField timePlayingField;
    // End of variables declaration//GEN-END:variables
}
